version: '3.5'


services:
  postgres:
    container_name: postgres_mns
    image: postgres:latest
    environment:
      POSTGRES_USER: micro-node-svc
      POSTGRES_PASSWORD: micro-node-svc
      PGDATA: /data/postgres
    volumes:
      - postgres-db:/data/postgres
    ports:
      - "5432:5432"


volumes:
  postgres-db:
    driver: local